# Generated by Django 4.2.3 on 2024-05-17 13:20

from django.db import migrations

class Migration(migrations.Migration):
    
    def create_profiles(apps, schema_editor):
        Profile = apps.get_model('back', 'Profile')
        User = apps.get_model('auth', 'User')
        for user in User.objects.all():
            Profile.objects.create(user_id=user)


    dependencies = [
        ('back', '0002_alter_profile_user_id'),
    ]

    operations = [
        migrations.RunPython(create_profiles)
        ]
