# Generated by Django 4.2.3 on 2024-01-23 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, verbose_name='Company name')),
                ('contact_person', models.CharField(max_length=32, verbose_name='Contact person')),
                ('unp', models.CharField(max_length=256, unique=True, verbose_name='UNP')),
                ('contact_info', models.CharField(max_length=256, verbose_name='Contact info')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, verbose_name='Company name')),
                ('contact_person', models.CharField(max_length=32, verbose_name='Contact person')),
                ('unp', models.CharField(max_length=256, unique=True, verbose_name='UNP')),
                ('contact_info', models.CharField(max_length=256, verbose_name='Contact info')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_shipment', models.DateTimeField(verbose_name='Date of shipment')),
                ('date_of_delivery', models.DateTimeField(verbose_name='Date of delivery')),
                ('customer_price', models.PositiveBigIntegerField(verbose_name='Customer price')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], verbose_name='Currency')),
                ('country_of_dispatch', models.CharField(max_length=128, verbose_name='Country of dispatch')),
                ('city_of_dispatch', models.CharField(max_length=128, verbose_name='City of dispatch')),
                ('address_of_dispatch', models.CharField(max_length=128, verbose_name='Address of dispatch')),
                ('delivery_country', models.CharField(max_length=128, verbose_name='Delivery country')),
                ('delivery_city', models.CharField(max_length=128, verbose_name='Delivery city')),
                ('delivery_address', models.CharField(max_length=128, verbose_name='Delivery address')),
                ('name_of_cargo', models.CharField(max_length=256, verbose_name='Name of cargo')),
                ('type_of_transport', models.CharField(max_length=256, verbose_name='Type of transport')),
                ('cargo_info', models.CharField(max_length=1000, verbose_name='Cargo info')),
                ('note', models.CharField(max_length=1000, verbose_name='Add-on info')),
                ('date_of_request', models.DateTimeField(auto_now_add=True, verbose_name='Date of request')),
                ('status', models.CharField(choices=[('created', 'Created'), ('On it', 'On it'), ('Archived', 'Archived')], verbose_name='Request status')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.carrier', verbose_name='Carrier')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Client')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Executor')),
            ],
        ),
    ]
