# Generated by Django 4.2.3 on 2024-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='rate',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Rate'),
            preserve_default=False,
        ),
    ]
