# Generated by Django 4.2.3 on 2024-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrier_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='cargo_info',
        ),
        migrations.AddField(
            model_name='request',
            name='height',
            field=models.CharField(default='', max_length=128, verbose_name='Height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='pallets',
            field=models.CharField(default='', max_length=128, verbose_name='Pallets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='volume',
            field=models.CharField(default='', max_length=128, verbose_name='Volume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='weight',
            field=models.CharField(default='', max_length=128, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='width',
            field=models.CharField(default='', max_length=128, verbose_name='Width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='yardage',
            field=models.CharField(default='', max_length=128, verbose_name='Yardage'),
            preserve_default=False,
        ),
    ]
