# Generated by Django 4.2.3 on 2024-01-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_request_cargo_info_request_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivery_region',
            field=models.CharField(default='', max_length=128, verbose_name='Delivery region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='region_of_dispatch',
            field=models.CharField(default='', max_length=128, verbose_name='Region of dispatch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='unp',
            field=models.CharField(error_messages={'unique': 'Клиент с таким УНП уже существует.'}, max_length=256, unique=True, verbose_name='UNP'),
        ),
    ]
