# Generated by Django 4.2.3 on 2024-01-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_request_delivery_region_request_region_of_dispatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('On it', 'On it'), ('Archived', 'Archived')], default='created', verbose_name='Request status'),
        ),
    ]
