# Generated by Django 4.2.3 on 2024-01-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_of_delivery',
            field=models.DateField(verbose_name='Date of delivery'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_of_shipment',
            field=models.DateField(verbose_name='Date of shipment'),
        ),
    ]
