# Generated by Django 4.2.3 on 2024-01-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_request_date_of_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], default='USD', verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Add-on info'),
        ),
    ]
