# Generated by Django 4.2.3 on 2024-02-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_carrier_currency_alter_request_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='unp',
            field=models.CharField(error_messages={'unique': 'Перевозчик с таким УНП уже существует.'}, max_length=256, unique=True, verbose_name='UNP'),
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('file', models.FileField(upload_to='requests/docs/')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.request')),
            ],
        ),
    ]
