# Generated by Django 4.2.3 on 2024-02-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_carrier_unp_docs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='request_id',
            new_name='request',
        ),
    ]
