# Generated by Django 4.2.3 on 2024-02-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_request_id_docs_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_from_carrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_from_client',
            field=models.BooleanField(default=False),
        ),
    ]
