# Generated by Django 4.2.3 on 2024-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_client_note_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='note',
            field=models.CharField(default='', verbose_name='Note'),
        ),
    ]
