# Generated by Django 4.2.3 on 2024-02-23 15:05

from django.db import migrations, models
import datetime as dt


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_carrier_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=dt.datetime.now(), verbose_name='Created date'),
            preserve_default=False,
        ),
    ]
