# Generated by Django 4.2.3 on 2024-02-23 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_client_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
    ]
