# Generated by Django 4.2.3 on 2024-02-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_carrier_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='app.request', verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('on it', 'On it'), ('archived', 'Archived'), ('complete', 'Complete')], default='created', verbose_name='Request status'),
        ),
    ]
