# Generated by Django 4.2.3 on 2024-02-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_request_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='rate',
            field=models.PositiveBigIntegerField(blank=True, verbose_name='Rate'),
        ),
    ]
