# Generated by Django 4.2.3 on 2024-03-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_alter_carrier_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name': 'Перевозчики', 'verbose_name_plural': 'Перевозчики'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Заказчики', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': 'Документы', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Запросы и Заказы', 'verbose_name_plural': 'Запросы и Заказы'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='delivery_region',
        ),
        migrations.RemoveField(
            model_name='request',
            name='region_of_dispatch',
        ),
        migrations.AlterField(
            model_name='carrier',
            name='company_name',
            field=models.CharField(max_length=256, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='contact_info',
            field=models.CharField(max_length=256, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='contact_person',
            field=models.CharField(max_length=32, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='note',
            field=models.CharField(default='', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='rate',
            field=models.PositiveBigIntegerField(blank=True, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='app.request', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='unp',
            field=models.CharField(error_messages={'unique': 'Перевозчик с таким УНП уже существует.'}, max_length=256, unique=True, verbose_name='УНП'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=256, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_info',
            field=models.CharField(max_length=256, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(max_length=32, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.CharField(default='', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='client',
            name='unp',
            field=models.CharField(error_messages={'unique': 'Клиент с таким УНП уже существует.'}, max_length=256, unique=True, verbose_name='УНП'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='file',
            field=models.FileField(upload_to='requests/docs/', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='name',
            field=models.CharField(verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.request', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='request',
            name='address_of_dispatch',
            field=models.CharField(max_length=128, verbose_name='Адрес отправки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.carrier', verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='request',
            name='city_of_dispatch',
            field=models.CharField(max_length=128, verbose_name='Город отправки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='request',
            name='country_of_dispatch',
            field=models.CharField(max_length=128, verbose_name='Страна отправки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer_price',
            field=models.PositiveBigIntegerField(verbose_name='Цена заказчика'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_of_delivery',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_of_request',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запроса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_of_shipment',
            field=models.DateField(verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='delivery_address',
            field=models.CharField(max_length=128, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='delivery_city',
            field=models.CharField(max_length=128, verbose_name='Город доставки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='delivery_country',
            field=models.CharField(max_length=128, verbose_name='Страна доставки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='request',
            name='height',
            field=models.CharField(max_length=128, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name_of_cargo',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='request',
            name='pallets',
            field=models.CharField(max_length=128, verbose_name='Палеты'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_from_carrier',
            field=models.BooleanField(default=False, verbose_name='Оплата от перевозчика'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_from_client',
            field=models.BooleanField(default=False, verbose_name='Оплата от заказчика'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('on it', 'On it'), ('archived', 'Archived'), ('complete', 'Complete')], default='created', verbose_name='Статус запроса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type_of_transport',
            field=models.CharField(max_length=256, verbose_name='Тип транспорта'),
        ),
        migrations.AlterField(
            model_name='request',
            name='volume',
            field=models.CharField(max_length=128, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='request',
            name='weight',
            field=models.CharField(max_length=128, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='request',
            name='width',
            field=models.CharField(max_length=128, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='request',
            name='yardage',
            field=models.CharField(max_length=128, verbose_name='Длина'),
        ),
    ]
