# Generated by Django 4.2.3 on 2024-04-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_request_address_of_dispatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('eur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rub', models.DecimalField(decimal_places=2, max_digits=6)),
                ('byn', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Валюты',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('created', 'создан'), ('on it', 'в работе'), ('archived', 'в архиве'), ('complete', 'выполнен')], default='created', verbose_name='Статус запроса'),
        ),
    ]
