# Generated by Django 4.2.3 on 2024-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_client_unp_client_unique_unp_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='note',
            field=models.CharField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.CharField(blank=True, verbose_name='Примечание'),
        ),
    ]
