# Generated by Django 4.2.3 on 2024-05-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_carrier_note_alter_client_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='carrier_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], default=0, verbose_name='Валюта перевозчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='carrier_rate',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Ставка перевозчика'),
            preserve_default=False,
        ),
    ]
