# Generated by Django 4.2.3 on 2024-05-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_request_carrier_currency_request_carrier_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='carrier_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], verbose_name='Валюта перевозчика'),
        ),
    ]
