# Generated by Django 4.2.3 on 2024-05-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_request_carrier_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='carrier_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], null=True, verbose_name='Валюта перевозчика'),
        ),
    ]
