# Generated by Django 4.2.3 on 2024-05-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_request_carrier_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='carrier_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], default='USD', verbose_name='Валюта перевозчика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='carrier_rate',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Ставка перевозчика'),
        ),
    ]
