# Generated by Django 4.2.3 on 2024-05-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_request_carrier_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='request_id',
        ),
    ]
