# Generated by Django 4.2.3 on 2024-05-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    

    dependencies = [
        ('app', '0029_remove_carrier_request_id'),
    ]
    
    

    operations = [
        migrations.CreateModel(
            name='RequestCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrier')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.request')),
            ],
        ),
        
    ]
