# Generated by Django 4.2.3 on 2024-05-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    def fill_model(apps, schema_editor):
        RequestCarrier = apps.get_model('app', 'RequestCarrier')
        Request = apps.get_model('app', 'Request')
        
        for el in Request.objects.all():
            RequestCarrier.objects.create(
                carrier_id=el.carrier, request_id=el.pk, carrier_rate=el.carrier.rate, carrier_currency=el.carrier.currency)

    dependencies = [
        ('app', '0029_remove_carrier_request_id'),
    ]
    
    def reverse(apps, schema_editor):
        pass

    operations = [
        migrations.CreateModel(
            name='RequestCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrier')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.request')),
            ],
        ),
        migrations.RunPython(fill_model, reverse)
    ]
