# Generated by Django 4.2.3 on 2024-05-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_requestcarrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='carrier_currency',
        ),
        migrations.RemoveField(
            model_name='request',
            name='carrier_rate',
        ),
        migrations.AddField(
            model_name='requestcarrier',
            name='carrier_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], verbose_name='Валюта перевозчика'),
        ),
        migrations.AddField(
            model_name='requestcarrier',
            name='carrier_rate',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Ставка перевозчика'),
        ),
    ]
