# Generated by Django 4.2.3 on 2024-05-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_request_carrier_currency_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='requestcarrier',
            constraint=models.UniqueConstraint(fields=('carrier_id', 'request_id'), name='unique_request_carrier', violation_error_message='Перевозчик уже добавлен в данный запрос'),
        ),
    ]
