# Generated by Django 4.2.3 on 2024-05-17 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_requestcarrier_unique_request_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.requestcarrier', verbose_name='Перевозчик'),
        ),
    ]
