# Generated by Django 4.2.3 on 2024-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    
    def fill_model(apps, schema_editor):
        RequestCarrier = apps.get_model('app', 'RequestCarrier')
        Request = apps.get_model('app', 'Request')
        
        for el in Request.objects.all():
            RequestCarrier.objects.create(
                carrier_id=el.carrier, request_id=el, carrier_rate=el.carrier.rate, carrier_currency=el.carrier.currency)
            
    def reverse(apps, schema_editor):
        pass

    dependencies = [
        ('app', '0033_alter_request_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcarrier',
            name='carrier_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('BYN', 'BYN')], default='BYN', verbose_name='Валюта перевозчика'),
        ),
        migrations.AlterField(
            model_name='requestcarrier',
            name='carrier_rate',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Ставка перевозчика'),
        ),
        migrations.RunPython(fill_model, reverse)
        
    ]
