# Generated by Django 4.2.3 on 2024-10-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_requestcarrier_carrier_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='contact_person',
            field=models.CharField(max_length=256, verbose_name='Контактное лицо'),
        ),
    ]
