# Generated by Django 4.2.3 on 2025-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_carrier_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='receive_doc_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата получения документов'),
        ),
    ]
