# Generated by Django 4.2.3 on 2025-03-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_request_receive_doc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('created', 'создан'), ('on it', 'в работе'), ('complete', 'выполнен')], default='created', verbose_name='Статус запроса'),
        ),
    ]
